spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:~/test5"
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
