spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:~/test"
    driverClassName: org.h2.Driver
    username: sa
    password:
    initializ: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
